config/routes.rb
Yakimapress::Application.routes.draw do
  # Redir all non-www to www
  constraints(:host => /^yakimapress.com$/) do
    root :to => redirect("http://www.yakimapress.com")
    match '/*path', :to => redirect {|params| "http://www.yakimapress.com/#{params[:path]}"}
  end

  devise_for :users

  # resources :faqs, :as =>faqs
  match '/frequently-asked-questions', :as => :faq_index, :to => 'faqs#index'
  resources 'f', :as => :faqs, :controller => :faqs


  # TODO -- younker [2011-03-30 10:28]
  # After I migrate all the ecommerce engine stuff in here, use this for seo reasons
  # match 'wine-and-cider-press', :as => :products, :via => :get, :to => 'products#index'
  # resources :products, :except => [:index] do
  #   resources :photos
  # end


  match '/about', :to => 'home#about', :as => :about
  match '/american-village-institute', :to => 'home#american_village_institute', :as => :american_village_institute

  root :to => 'home#home', :as => :home
  root :to => 'home#home', :as => :root

  match '/generate-permalink', :as => 'generate_permalink', :to => 'home#generate_permalink'


  # Hmmmm, if we have this, we lose the contact paths given to us by the contact engine
  # match '*path' => 'products#by_permalink'

end

app/models/faq.rb
class Faq < ActiveRecord::Base

  validates_presence_of :question, :answer, :permalink

end

app/controllers/faqs_controller.rb
class FaqsController < InheritedResources::Base
  before_filter :redirect_unless_admin, :except => [:index, :show]

  before_filter :set_faq, :except => [:index, :new, :create]
  before_filter :set_canonical, :only => [:show]

  include FaqsHelper

  def create
    create! do |format|
      format.html { redirect_to faq_path(@faq.permalink) }
    end
  end

  def update
    update! do |format|
      format.html { redirect_to faq_path(@faq.permalink) }
    end
  end
  
  def set_faq
    @faq = Faq.find_by_permalink(params['id']) || Faq.find_by_id(params['id'])
  end

  def set_canonical
    @canonical = faq_url(@faq.permalink) unless faq_path(@faq.permalink) == request.path
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper

end

app/views/faqs/_form.html.haml
= form_for @faq, :html => {:class => 'faq scaffold'} do |f|
  = render :partial => 'shared/user_notice', :locals => {:model_obj => @faq}

  .field.quarterh
    = f.label :question
    = f.text_area :question

  .field.halfh
    = f.label :answer
    = f.text_area :answer

  - if @faq.new_record?
    .field
      - auto = link_to 'autogenerate based on question', generate_permalink_path, :class => 'autogen'
      = f.label :permalink, "Permalink #{auto}".html_safe
      = f.text_field :permalink
    
  - else
    .field
      = f.label :permalink
      %div.disabled_form_field= @faq.permalink


  .actions.clearfix
    = f.submit 'Submit', :class => :button


:javascript
  $('a.autogen').get_permalink_version({
    source : $('textarea#faq_question'),
    target : $('input#faq_permalink')
  })

app/views/faqs/edit.html.haml
%h1 Editing faq

= render 'form'

= link_to 'Cancel and create New Faq', new_faq_path

app/views/faqs/index.html.haml
:ruby
  page_title('Frequently Asked Questions')
  header(:title, 'FAQ')
  header(:description, "Frequently asked questions about cider presses, the American Harvester double tub, wine presses, the Original Villager Wine Press and more.")


%div#faqC.clearfix.container
  %div.span-8 &nbsp;
  %div.span-32
    - if @faqs.empty?
      Sorry, but there are currently no frequently asked questions! Please check back soon.
    - else
      %ul
        = render :partial => 'faqs/index/faq', :collection => @faqs
  

  %div.span-8.last
    = admin_area do
      = link_to 'New Faq', new_faq_path

app/views/faqs/new.html.haml
%h1 New faq

= render 'form'

= link_to 'Cancel', faqs_path

app/views/faqs/show.html.haml
:ruby
  page_title(@faq.question, 'faq_page')
  header(:title, @faq.permalink.titleize)
  header(:description, "(Question) #{@faq.question} (Answer) #{@faq.answer}")


%div#faqC.clearfix.container
  %div.span-8 &nbsp;
  %div.span-32
    = sanitize @faq.answer, :tags => %w(br p a b ul li), :attributes => %w(href)

  %div.span-8.last
    = admin_area do
      = link_to 'Edit', edit_faq_path(@faq)
      |
      = link_to 'Destroy', @faq, :confirm => 'Are you sure?', :method => :delete