config/routes.rb
Yakimapress::Application.routes.draw do
  # Redir all non-www to www
  constraints(:host => /^yakimapress.com$/) do
    root :to => redirect("http://www.yakimapress.com")
    match '/*path', :to => redirect {|params| "http://www.yakimapress.com/#{params[:path]}"}
  end

  devise_for :users

  # resources :faqs, :as =>faqs
  match '/frequently-asked-questions', :as => :faq_index, :to => 'faqs#index'
  resources 'f', :as => :faqs, :controller => :faqs


  # TODO -- younker [2011-03-30 10:28]
  # After I migrate all the ecommerce engine stuff in here, use this for seo reasons
  # match 'wine-and-cider-press', :as => :products, :via => :get, :to => 'products#index'
  # resources :products, :except => [:index] do
  #   resources :photos
  # end


  match '/about', :to => 'home#about', :as => :about
  match '/american-village-institute', :to => 'home#american_village_institute', :as => :american_village_institute

  root :to => 'home#home', :as => :home
  root :to => 'home#home', :as => :root

  match '/generate-permalink', :as => 'generate_permalink', :to => 'home#generate_permalink'


  # Hmmmm, if we have this, we lose the contact paths given to us by the contact engine
  # match '*path' => 'products#by_permalink'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
    @wine_press = Product.find_by_permalink('villager-wine-press')
    @cider_press = Product.find_by_permalink('colonial-cider-mill-apple-press')
  end

  def about
  end

  def american_village_institute
  end

  def generate_permalink
    render :text => params[:string].present? ? params[:string].make_url_friendly : nil
  end

end

app/helpers/home_helper.rb
module HomeHelper
  def images_for_slideshow(type)
    image_dir = "/images/home/imageshow/#{type}"
    d = "#{Rails.root}/public#{image_dir}"
    if File.directory?(d)
      Dir.entries(d).select{|i| i.match(/\.png/) }.collect{ |i| "#{image_dir}/#{i}" }
    else
      []
    end
  end
end

app/views/home/about.haml
:ruby
  page_title("Our story begins in the Yakima Valley with a passion for wine and cider.")
  header(:title, 'About')
  header(:description, 'The cider and wine presses manufactured by Yakima Press Company are built from a tradition that started in 1975 and are 100% American made.')


%div#aboutC.container
  %div.prepend-5.span-38.append-5
    %h2 History

    %div.span-38.last
      %div.span-18.append-2
        The cider and wine presses manufactured by Yakima Press Company are built from a tradition that started in 1975
        = "with the birth of the #{link_to 'American Village Institute', american_village_institute_path}.".html_safe
        Located in the Northeast corner of Washington State, the Institute was formed by a small group of “villagers”
        who were dedicated to teaching others how to become more self-sufficient, not only as individuals, but also how
        to create self sufficient communities, or villages. Under this concept the American Village Institute creating a
        number of hand and foot operated tools, including cider presses, wine presses, corn shellers, root cutters,
        flour mills, and many other tools. The Institute’s aim was to develop a contemporary version of the tools

      %div.span-18.last
        needed to become self-sufficient while incorporating modern technology and knowledge. In the1980’s
        William (Bill) Courtis, a former professor at the American Village Institute, and a partner purchased most of the
        Institutes assets after the American Village Institute ceased to operate. Bill has spent the last 25 years building
        cider and wine presses in the same town where it all started. He hand crafts each press from start to finish at his
        shop, The Phoenix Foundry, which includes a complete foundry, woodworking shop, and machine shop. Thankfully, Bill has
        passed on his experience, knowledge, and skills to allow the tradition to continue through the Yakima Press Company.

    %h2 Yakima Press Company

    %div.span-38.last
      %div.span-18.append-2
        Located in the heart of apple country, Yakima Press Company was formed to carry on traditions that started with the
        birth of America. Apple cider has a long history, dating back to Roman times, but in Colonial America cider was the
        most common beverage. As water was unsafe in many areas, cider was drank by everyone, and even used for paying tithes,
        taxes, and wages. Due to a variety of factors, cider production fell dramatically

      %div.span-18.last
        around the turn of the 1900’s and dropped even further with prohibition. Recently, we have seen an increased
        awareness and interest in both sweet and hard cider. Regardless of trends, Yakima Press Company is dedicated to
        manufacturing the highest quality cider and wine presses in the industry. Each handcrafted cider and/or wine
        press is proudly made in the USA.

    %h2 Contact

    %div#contactC.container
      %div.span-16
        %div.span-16.last
          %b Yakima Press Company, LLC

        %div.span-5 Phone:
        %div.span-10.last 509-480-0642

        %div.span-5 Email:
        %div.span-10.last= "#{mail_to 'info@yakimapress.com'} <br /> #{link_to 'website contact us form', contact_path}".html_safe

        %div.span-5 Address:
        %div.span-10.last 361 Charlie Lane

        %div.span-5 &nbsp;
        %div.span-10.last Naches, Washington 98937 USA

      %div.span-22
        :plain
          <iframe width="425" height="300" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Naches,+WA&amp;aq=0&amp;sll=37.0625,-95.677068&amp;sspn=52.947994,76.201172&amp;ie=UTF8&amp;hq=&amp;hnear=Naches,+Yakima,+Washington&amp;ll=46.730958,-120.699516&amp;spn=10.980957,19.050293&amp;z=6&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Naches,+WA&amp;aq=0&amp;sll=37.0625,-95.677068&amp;sspn=52.947994,76.201172&amp;ie=UTF8&amp;hq=&amp;hnear=Naches,+Yakima,+Washington&amp;ll=46.730958,-120.699516&amp;spn=10.980957,19.050293&amp;z=6" style="color:#0000FF;text-align:left">View Larger Map</a></small>

app/views/home/american_village_institute.haml
:ruby
  page_title("American Village Institute – A Village Concept")
  header(:title, "American Village Institute")
  header(:description, "American Village Institute -- A Village Concept and perhaps the most unusual nonprofit research and education organization currently active.")


%div#aviC.container.prepend-6.span-36.append-6
  %b By William R. Lawson
  %p In many ways the American Village Institute is perhaps the most unusual nonprofit research and educational organization currently active in the field of alternative. Young, but rapidly growing, the AVI was begun in early 1975 by a small group of dedicated “villagers” who saw the need for a comprehensive institute devoted to teaching people how to become more self sufficient. Not just to be self sufficient individuals, but also how to create reasonably self sufficient communities. It is this emphasis on small community, or village, development that lies at the heart of the AVI concept. 
  %p In order to fully understand the objectives of the AVI, it is first necessary to understand what is meant by the term “village.” In brief, a village is defined as a simple composite of family farms, trades people, and a marketplace. It is further distinguished by the fact that most of its inhabitants can and do provide most of their own basic necessities, and at least some of their niceties. It is also perhaps the largest form of socioeconomic grouping that can still function entirely on the basis of trade, barter, and the exchange of labor. 
  %p With this definition it is easy to see how the village concept can provide a very useful framework for exploring the entire area of self sufficiency and appropriate technology. By using this village approach, the AVI is developing a broad research and educational program that has many innovative features. One of the most important of these has to do with the study and design of appropriate tools and equipment, and the teaching of the skills necessary to make and use them. 
  %p To begin with, the Institute is mostly interested in the development of those tools and methods that are ordinarily associated with traditional crafts, trades, and skills. The reason is simple: no one can be any more self sufficient than if they can provide their own food, clothing, and shelter, as well as their own tools. [Prior to the industrial revolution that is exactly what most people did – at least within their village structure.] At the same time, the best way to learn these skills is to study them under the guidance of someone who has already mastered them. With this in view, the AVI has begun a comprehensive apprenticeship program that encourages each student to master at least one craft or trade, and gain at least a working familiarity with all the skills necessary to provide the basics of food, clothing, shelter, and tools. Although still in the initial phase of development, it is envisioned that each student who completes the entire course will have the knowledge and ability to create a very comfortable, yet highly self sufficient way of life.
  %p This focus on tools and related technology is not accidental. In fact, one of the primary reasons the AVI was established was because there were no longer any sources for many of the hand and foot operated tools and equipment common to rural America up until the 1940’s. The object from the beginning was threefold: first, to make available many of these items that have faded into the past (or are collecting dust in antique shops); second, to reintroduce a new standard of quality in design, craftsmanship and materials; and third, to provide a reliable method of funding for an apprentice-style craft and trade school. Specific products have not only been selected because of their traditional use, but also because they require a broad range of craft and skills in the making. They also reflect the type and range of products many students will begin producing once they have established their own shops.
  %p In addition to making traditional tools and equipment, the Institute has also begun to develop many of the older methods and processes that were originally used to make the tools. This begins with the basic methods of extracting and refining raw materials and carries through the last touches on the final product. For the most part, the emphasis is on the use of hand and foot power – through there is also an attempt to recreate and / or improve upon earlier uses of water, wind, and animal power. This work is aimed at developing a contemporary version of all the tools, hardware, and technology that were typical of an average early American Village – as well as the knowledge and skills necessary to use them. The object is not to recreate the past out of curiosity, but rather to regain much of what has been forgotten and integrate that knowledge with what is being learned today.
  %p In addition to the apprenticeship program, the Institute is also developing a more general course of instruction in applied (appropriate) technology. This program was scheduled to begin in early October 1977 and to include a variety of subjects ranging from organic farming to the design and construction of energy efficient architecture. The emphasis is on teaching the underlying principles upon which all technology is based, and how to apply those principles in the development of contemporary manual that will cover all aspects of self sufficiency at both the family and village levels. Other publications, like the Institutes bimonthly magazine The Cider Press, are intended to provide a more general view of how self sufficiency can be related to a contemporary village structure.
  %p Perhaps one of the most unique features of the AVI is its growing membership program. Based on the belief that more people will become self sufficient once it is technically and financially easier to do so, this program offers members the opportunity to contribute their own time, energy, and talents to the overall AVI effort – and in return, receive all the benefits that this combined effort can produce. In many respects this cooperative approach allows individual members to get back considerably more than they put in. It also dramatically increases the effectiveness of the entire organization. For Example, the apprenticeship program is open to all members tuition-free (including room & board; in turn, they products made by the apprentices during the course of their training are available to the general membership for the cost of producing them (no profit is added). This serves the dual purpose of providing free training for those who desire it, and highly crafted, exceptionally low-cost tools and equipment for those who need them. 
  %p The membership program also provides a much needed outlet for the many creative people throughout the country who would like to become involved in alternative research and education, but may have been unable to find an organization that can translate their energies into constructive projects. Mush of the Institute’s research, as well as material for publications, comes from the more than 3,000 members in the United States and many foreign countries. Participating members from many universities, industries, craft shops, and farms across the country provide the Institute with a steady influx of permanent members of the Institute’s faculty and staff. 
  %p In brief, the village concept has begun to excite the imagination of people everywhere, in every walk of life. It not only provides a framework for the development of appropriate tools and technology, but also promises to become the most direct way for many people to achieve a greater level of control over their basic needs. By working within this concept, the American Village Institute has begun to create a new direction that can get people involved in a very meaningful way. Because of this cooperative approach, the AVI has become a powerful catalyst for change.

app/views/home/home.haml
:ruby
  page_title('Vintage cider and wine presses')
  header(:title, 'Cider & Wine Presses')
  header(:description, 'Yakima Press Company builds the 100% American made Colonial™ Cider Mill and Villager™ Wine Press, designed for both beginners and enthusiasts.')

%div#productsC.container
  %div.span-48.last
    %div#wine_pressC.span-18
      %h1 Wine Press
      %div.descrC
        = @wine_press.descr.truncate(300, "...continue on our #{permalink(@wine_press)} page.").html_safe

      %div.flagged
        %span= "View the #{permalink(@wine_press)}".html_safe
      %div#wineIS.imageshowC
        - images_for_slideshow('wine').each do |image_path|
          = image_tag image_path


    %div.span-12
      = image_tag "home/yakima-press-company.jpg", :id => 'main_product_image', :alt => 'Yakima Press Company'


    %div#cider_pressC.span-18.last
      %h1 Cider Press
      %div.descrC
        = @cider_press.descr.truncate(300, "...continue on our #{permalink(@cider_press)} page.").html_safe

      %div.flagged
        %span= "View the #{permalink(@cider_press)}".html_safe

      %div#ciderIS.imageshowC
        - images_for_slideshow(@cider_press.press_type).each do |image_path|
          = image_tag image_path



:javascript
  $(document).ready(function() {
    new Imageshow($('#wineIS'));
    new Imageshow($('#ciderIS'), {wait : 2500});
  })